<?php

  require_once (dirname(__FILE__).'/../../helpers/NavigationHelper.php');
  $objHelper = new NavigationHelper();

?>
            <script type="text/javascript">//<![CDATA[
              rootLevelId = <?php echo $this->rootLevelId; ?>;
              rootLevelGroupId = <?php echo $this->rootLevelGroupId; ?>;
              folderFormDefaultId = '<?php echo $this->folderFormDefaultId; ?>';
              elementFormDefaultId = '<?php echo $this->elementFormDefaultId; ?>';
              elementTemplateDefaultId = '<?php echo $this->elementTemplateDefaultId; ?>';
              elementTypeDefaultId = <?php echo $this->elementTypeDefaultId; ?>;           
            //]]>
            </script>
    
            <div id="level<?php echo $this->currLevel; ?>" class="navlevelinner" onmouseover="myNavigation.toggleAddMenuIcon(<?php echo $this->currLevel; ?>,'show');return false;" onmouseout="myNavigation.toggleAddMenuIcon(<?php echo $this->currLevel; ?>,'hide'); return false;">
              <?php echo $objHelper->getNavigationElements($this->rootelements, $this->currLevel, $this->rootLevelGroupKey); ?>
              <div>&nbsp;</div>
            </div>

            <div id="levelmenu<?php echo $this->currLevel; ?>" class="levelmenu" style="display:none;" onclick="myNavigation.showAddMenu(<?php echo $this->currLevel; ?>); return false;" onmouseover="myNavigation.toggleAddMenuIcon(<?php echo $this->currLevel; ?>,'show');return false;">
              <div><img src="/zoolu-statics/images/icons/icon_add.png" width="16" height="16" alt="<?php echo $this->translate->_('Show_Add_Menu'); ?>"/></div>
            </div>

            <div id="addmenu<?php echo $this->currLevel; ?>" class="addmenu" style="display:none;">
              <div class="addmenutopleft"></div>
              <div class="addmenutopright"></div>
              <div class="clear"></div>
              <div class="addmenucontent">
                 <div class="addmenuelement" onclick="myNavigation.addFolder(<?php echo $this->currLevel; ?>); return false;">
                  <img class="icon" src="/zoolu-statics/images/icons/icon_folder_new.png" width="16" height="16" alt="<?php echo $this->translate->_('New_Folder'); ?>"/>
                  <div class="small white"><?php echo $this->translate->_('New_Folder'); ?></div>
                  <div class="clear"></div>
                </div>
              </div>
            </div>


