        <?php if($this->pageurl != '') : ?>
        <div class="pagepreviewcontainer">
          <div class="pagepreviewcenter white small"><a href="<?php echo $this->pageurl; ?>" target="_blank"><img src="/zoolu-statics/images/icons/icon_page_preview.png"/><?php echo $this->translate->_('Test_page'); ?></a></div>
					<?php if($this->backLink): ?>
					<div class="pagebackcenter white small"><a onclick="myNavigation.selectNavigationItem(<?php echo $this->currLevel - 1; ?>, 'folder', <?php echo $this->parentFolderId; ?>, false); myFolder.getFolderContentList(); return false;" target="_blank"><img src="/zoolu-statics/images/icons/icon_page_preview.png"/><?php echo $this->translate->_('Back'); ?></a></div>
					<div class="clear"></div>
					<? endif; ?>
          <div class="clear"></div>
				</div>
        <?php endif; ?>
        <?php if($this->languageOptions != '') : ?>
        <div class="languagecontainer">
          <select id="selectLanguageId" onchange="myForm.changeLanguage(this.value<?php if($this->backLink) echo ', true'; ?>); return false;">
            <?php echo $this->languageOptions; ?>
          </select>
        </div>
        <?php endif; ?>
        <div class="formtitle"><?php echo $this->formtitle; ?></div>
        <?php echo $this->form; ?>
				<div class="clear"></div>
				<div style="display:none;" id="divMetaInfos">
          <table cellpadding="0" cellspacing="0">
            <?php if(!$this->blnIsStartPage) : ?>
            <tr>
              <td class="tdImportant"><?php echo $this->translate->_('Status'); ?>:</td>
              <td>
                <select id="statusSelect" class="important" onchange="$('idStatus').setValue(this.value); return false;">
                  <?php echo $this->statusOptions; ?>
                </select>
              </td>
            </tr>
            <?php endif; ?>
            <tr id="trChangeType">
              <td class="tdNormal"><?php echo $this->translate->_('Type'); ?>:</td>
              <td id="tdChangeType">
                <select id="creatorSelect" class="normal" onchange="myPage.changeType(this.value<?php if($this->backLink) echo ', true'; ?>); return false;">
                  <?php echo $this->typeOptions; ?>
                </select>
              </td>
            </tr>
            <?php if(!$this->blnIsStartPage) : ?>
            <tr>
              <td class="tdNormal"><?php echo $this->translate->_('show_in'); ?></td>
              <td class="tdShow">
                <input type="checkbox" name="showinnavigation" id="showinnavigation"<?php ($this->showinnavigation > 0) ? print(' checked="checked"') : ''; ?> onclick="if($('divShowInNavigationOptions')) { myForm.toggleNavigationOptions(this); } else { $('showInNavigation').value = (this.checked) ? '1' : '0'; }"/>
                <label for="showinnavigation"><?php echo $this->translate->_('show_in_navigation'); ?></label>
                <?php if($this->blnIsRootLevelChild): ?>
                <div id="divShowInNavigationOptions"<?php echo ($this->showinnavigation == 0) ? ' style="display:none;"' : ''; ?>>
                  <div class="navigationoptios">
                    <select name="showinnavigationoption" id="showinnavigationoption" onchange="$('showInNavigation').value = this.value;">
                      <?php echo $this->navigationOptions; ?>
                    </select>
                  </div>
                </div>
                <?php endif;?>
              </td>
            </tr>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td class="tdShow">
                <input type="checkbox" name="shownonlyfordestination" id="shownonlyfordestination"<?php ($this->destinationId > 0) ? print(' checked="checked"') : ''; ?> onclick="myForm.toggleDestinationOptions(this);"/>
                <label for="shownonlyfordestination"><?php echo $this->translate->_('show_only_for_region'); ?></label>
                <div id="divShownOnlyForDestinationOptions"<?php echo ($this->destinationId == 0) ? ' style="display:none;"' : ''; ?>>
                  <div class="navigationoptios">
                    <select name="shownonlyfordestinationoption" id="shownonlyfordestinationoption" onchange="$('destinationId').value = this.value;">
                      <?php echo $this->destinationOptions; ?>
                    </select>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td class="tdShow">
                <input type="checkbox" name="hideinsitemap" id="hideinsitemap"<?php ($this->hideInSitemap > 0) ? print(' checked="checked"') : ''; ?> onclick="if($('hideInSitemap')) $('hideInSitemap').value = (this.checked) ? '1' : '0';"/>
                <label for="hideinsitemap"><?php echo $this->translate->_('hide_in_sitemap'); ?></label>
              </td>
            </tr>
            <?php if($this->showDisplayTypes == 'true'): ?>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td class="tdShow">
                <input type="checkbox" name="showinwebsite" id="showinwebsite"<?php ($this->showInWebsite > 0) ? print(' checked="checked"') : ''; ?> onclick="if($('showInWebsite')) $('showInWebsite').value = (this.checked) ? '1' : '0';"/>
                <label for="showinwebsite"><?php echo $this->translate->_('show_in_website'); ?></label>
              </td>
            </tr>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td class="tdShow">
                <input type="checkbox" name="showintablet" id="showintablet"<?php ($this->showInTablet > 0) ? print(' checked="checked"') : ''; ?> onclick="if($('showInTablet')) $('showInTablet').value = (this.checked) ? '1' : '0';"/>
                <label for="showintablet"><?php echo $this->translate->_('show_in_tablet'); ?></label>
              </td>
            </tr>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td class="tdShow">
                <input type="checkbox" name="showinmobile" id="showinmobile"<?php ($this->showInMobile > 0) ? print(' checked="checked"') : ''; ?> onclick="if($('showInMobile')) $('showInMobile').value = (this.checked) ? '1' : '0';"/>
                <label for="showinmobile"><?php echo $this->translate->_('show_in_mobile'); ?></label>
              </td>
            </tr>
            <?php endif; ?>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td>
                <a href="#" onclick="myForm.getCopyLanguageChooser(); return false;"><?php echo $this->translate->_('language_copy') ?></a>
              </td>
            </tr>
            <tr>
              <td class="tdNormal"><?php echo $this->translate->_('Published'); ?>:</td>
              <td>
                <div class="publishdate" id="divPublishDate"><?php echo $this->publishDate; ?></div>
                <img class="iconcalendar" src="/zoolu-statics/images/icons/icon_calendar_purple.png" onclick="myForm.togglePublishDate(); return false;" width="13" height="15"/>
                <div class="clear"></div>
                <div id="divPublishDateNew" style="display:none;">
                  <div class="divpublishnewdateinner">
                    <div class="divpublishnewdatetop"><img src="/zoolu-statics/images/main/bg_box_147_top.png" width="147" height="4" /></div>
                    <div class="newdate">
                      <input type="text" maxlength="2" value="<?php echo $this->arrPublishDate['day']; ?>" name="publishDay" id="publishDay"/>.<select name="publishMonth" id="publishMonth">
	                      <?php echo $this->monthOptions; ?>
                      </select>
                      <input type="text" class="year" maxlength="4" value="<?php echo $this->arrPublishDate['year']; ?>" name="publishYear" id="publishYear"/>
                      <div class="clear"></div>
                    </div>
                    <div class="newtime">
                      <div class="newtimeinner"><input type="text" maxlength="2" value="<?php echo $this->arrPublishDate['hour']; ?>" name="publishHour" id="publishHour"/>:<input type="text" maxlength="2" value="<?php echo $this->arrPublishDate['minute']; ?>" name="publishMinute" id="publishMinute"/></div>
                      <div id="buttonassume" onclick="myForm.writePublishDate();">
                        <div class="button17leftOff"></div>
			                  <div class="button17centerOff">
			                    <div><?php echo $this->translate->_('Apply'); ?></div>
			                    <div class="clear"></div>
			                  </div>
                        <div class="button17rightOff"></div>
                        <div class="clear"></div>
                      </div>
                      <div class="clear"></div>
                    </div>
                    <div class="divpublishnewdatebottom"><img src="/zoolu-statics/images/main/bg_box_147_bottom.png" width="147" height="4" /></div>
                    <div class="clear"></div>
                  </div>
                  <div class="clear"></div>
                </div>
              </td>
            </tr>
            <!--
            <tr>
              <td class="tdNormal"><?php echo $this->translate->_('Security'); ?>:</td>
              <td>
                <select class="normal">
                  <option value="1">&Ouml;ffentlich</option>
                  <option value="2">Privat</option>
                </select>
              </td>
            </tr>
            -->
            <tr>
              <td class="tdNormal"><?php echo $this->translate->_('Author'); ?>:</td>
              <td>
                <select id="creatorSelect" class="normal" onchange="$('creator').setValue(this.value); return false;">
                  <?php echo $this->creatorOptions; ?>
                </select>
              </td>
            </tr>
            <?php endif; ?>
            <?php if($this->version > 0) : ?>
            <tr>
              <td class="tdNormal"><?php echo $this->translate->_('Version'); ?>:</td>
              <td>
                <div class="currversion"><?php echo $this->version; ?>.0</div>
                <!-- <div id="buttonnewversion">
                  <div class="button17leftOff"></div>
                  <div class="button17centerOff">
                    <img src="/zoolu-statics/images/icons/icon_plus_white_small.png" width="8" height="8"/>
                    <div><?php echo $this->translate->_('New_version'); ?></div>
                  </div>
                  <div class="button17rightOff"></div>
                </div> -->
                <div class="clear"></div>
              </td>
            </tr>
            <?php endif; ?>
            <?php if($this->changeUser != '' && $this->changeDate != '') : ?>
            <tr>
              <td class="tdNormal"><?php echo $this->translate->_('Last_change'); ?>:</td>
              <td><?php echo $this->changeDate; ?><br/><?php echo $this->changeUser; ?></td>
            </tr>
            <?php endif; ?>
            <?php if($this->version > 1) : ?>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td><a href="#"><?php echo $this->translate->_('Version_list'); ?></a></td>
            </tr>
            <?php endif; ?>
            <tr>
              <td class="tdNormal">&nbsp;</td>
              <td>
                <a href="#" onclick="myDashboard.getSendToDashboard(); return false;"><?php echo $this->translate->_('Send_to_dashboard') ?></a>
              </td>
            </tr>
          </table>
        </div>
        <script type="text/javascript">//<![CDATA[
          myForm.blnShowFormAlert = <?php echo (($this->blnShowFormAlert == true) ? 'true' : 'false') ?>;
          myForm.selectNavigationItemNow = <?php echo (($this->selectNavigationItemNow && $this->selectNavigationItemNow == true) ? 'true' : 'false') ?>;
          myForm.isAuthorizedToDelete(<?php echo (($this->authorizedDelete && $this->authorizedDelete == true) ? 'true' : 'false') ?>);
          myForm.isAuthorizedToUpdate(<?php echo (($this->authorizedUpdate && $this->authorizedUpdate == true) ? 'true' : 'false') ?>);
          <?php if($this->itemId): ?>myNavigation.itemId = '<?php echo $this->itemId ?>';<?php endif; ?>
          myPage.isStartPage = <?php echo (($this->blnIsStartPage == true) ? 'true' : 'false') ?>;         
          //]]>
        </script>