<?php

  require_once (dirname(__FILE__).'/../../helpers/ViewHelper.php');
  $objHelper = new ViewHelper();
  
  echo $objHelper->getThumbView($this->objFiles, $this->sliderValue);

?> 
  <script type="text/javascript">//<![CDATA[
    myMedia.isAuthorizedToAdd(<?php echo (($this->authorizedAdd && $this->authorizedAdd == true) ? 'true' : 'false') ?>);
    myMedia.isAuthorizedToDelete(<?php echo (($this->authorizedDelete && $this->authorizedDelete == true) ? 'true' : 'false') ?>);
    myMedia.isAuthorizedToUpdate(<?php echo (($this->authorizedUpdate && $this->authorizedUpdate == true) ? 'true' : 'false') ?>);
  //]]>
  </script>