<?php
  require_once (dirname(__FILE__).'/../../helpers/ListHelper.php');
  $objHelper = new ListHelper();
?>
<?php echo $objHelper->getTagsList($this->tagsPaginator, $this->orderColumn, $this->sortOrder, $this->searchValue, $this->countResult); ?>
<?php echo $this->paginationControl($this->tagsPaginator, 'Sliding', 'pagination.phtml'); ?>
<div class="spacer2"></div>
<script type="text/javascript">//<![CDATA[
  myForm.blnShowFormAlert = <?php echo (($this->blnShowFormAlert == true) ? 'true' : 'false') ?>;
  myCore.deleteAlertMultiMessage = 'Wollen Sie diese %i Tags l&ouml;schen?';
  myCore.deleteAlertSingleMessage = 'Wollen Sie diesen Tag l&ouml;schen?';
//]]>
</script>