<center>
<form id="loginForm" method="post" action="/login">
    <h1>Anmelden</h1>

    <div class="label">Username</div>
    <input type="text" value="" name="username" id="username">

    <div class="label">Passwort</div>
    <input type="password" name="password" id="password">
    <br>
    <input type="submit" value="Anmelden" class="bewerben-link" id="submit" name="submit">
</form>
</center>
