<html>
<head>

</head>
<body>
<p>
    Hallo,<br><br>

    sie haben sich auf unserer Webseite angegeben ihr Passwort vergessen zu haben. Um diesen Vorgang zu vervollständigen
    klicken Sie bitte auf folgenden Link:<br/>
    <a href="<?php echo $this->url; ?>"><?php echo $this->url; ?></a>

    <p>Falls Sie ihr Password nicht ändern wollen, ignorieren Sie dieses Mail einfach.</p>
</p>
</body>
</html>