<div class="contentContainer">
    <div class="inner">
        <h1>Registrierung</h1>

        <?php if ($this->display == 'confirmation'): ?>
        <p>Bestätigungsmail verschickt.</p>
        <?php elseif ($this->display == 'keyConfirmation'): ?>
        <p>Registrierung erfolgreich abgeschlossen.</p>
        <?php elseif ($this->display == 'invalidKey'): ?>
        <p>Dieser Link ist nicht mehr gültig!</p>
        <?php else: ?>
        <div class="register">
            <form action="/register?re=<?php echo urlencode($this->redirectUrl) ?>" method="post" id="registerForm">

                <div class="element">
                    <label for="fname">Vorname</label>
                    <input type="text" id="fname" name="fname" value="<?php echo $this->fname ?>"/>

                    <div class="error">
                        <?php echo $this->errFname ?>
                    </div>
                </div>

                <div class="element">
                    <label for="sname">Nachname</label>
                    <input type="text" id="sname" name="sname" value="<?php echo $this->sname ?>"/>

                    <div class="error">
                        <?php echo $this->errSname ?>
                    </div>
                </div>

                <div class="element">
                    <label for="email">Email *</label>
                    <input type="text" id="email" name="email" value="<?php echo $this->email ?>"/>

                    <div class="error">
                        <?php echo $this->errEmail ?>
                    </div>
                </div>

                <div class="element">
                    <label for="username">Benutzername *</label>
                    <input type="text" id="username" name="username" value="<?php echo $this->username ?>"/>

                    <div class="error">
                        <?php echo $this->errUsername ?>
                    </div>
                </div>

                <div class="element">
                    <label for="password">Passwort *</label>
                    <input type="password" id="password" name="password"/>

                    <div class="error">
                        <?php echo $this->errPassword ?>
                    </div>
                </div>

                <div class="element">
                    <label for="passwordConfirm">Passwort bestätigen *</label>
                    <input type="password" id="passwordConfirm" name="passwordConfirm"/>

                    <div class="error">
                        <?php echo $this->errPasswordConfirm ?>
                    </div>
                </div>

                <input type="submit" name="submit" id="submit" class="button" value="Absenden"/>
            </form>
        </div>
        <?php endif; ?>
    </div>
</div>