<div class="contentContainer">
    <div class="inner">
        <h1>Password zurücksetzen</h1>

        <div class="login">
            <form action="/reset" method="post" id="loginForm">
                <div class="element">
                    <label for="email">Email-Adresse</label>
                    <input type="text" id="email" name="email" />
                </div>

                <input type="submit" name="submit" id="submit" class="button" value="Absenden" />
            </form>
        </div>
    </div>
</div>