<div class="contentContainer">
    <div class="inner">
        <h1>Password zurücksetzen</h1>

        <?php if ($this->display == 'confirmation'): ?>
        <p>Bitte klicken Sie auf den Link im soeben verschickten Email, um ein neues Passwort einzugeben.</p>
        <?php elseif ($this->display == 'changePassword'): ?>
        <div class="login">
            <form action="/reset?key=<?php echo $this->key; ?>" method="post" id="loginForm">
                <div class="element">
                    <label for="password">Neues Passwort</label>
                    <input type="password" id="password" name="password"/>
                </div>
                <div class="element">
                    <label for="passwordConfirmation">Neues Password wiederholen</label>
                    <input type="password" id="passwordConfirmation" name="passwordConfirmation"/>

                    <div class="error">
                        <?php echo $this->errPassword ?>
                    </div>
                </div>

                <input type="submit" name="submit" id="submit" class="button" value="Absenden"/>
            </form>
        </div>
        <?php elseif ($this->display == 'changeConfirmation'): ?>
        <p>Passwort erfolgreich geändert.</p>
        <?php else: ?>
        <div class="login">
            <form action="/reset" method="post" id="loginForm">
                <div class="element">
                    <label for="email">Email-Adresse</label>
                    <input type="text" id="email" name="email"/>

                    <div class="error">
                        <?php echo $this->errEmail ?>
                    </div>
                </div>

                <input type="submit" name="submit" id="submit" class="button" value="Absenden"/>
            </form>
        </div>
        <?php endif; ?>
    </div>
</div>