<html>
<head>

</head>
<body>
<?php if ($this->status == 1): ?>
<p>
    Hallo, <br /><br />
    Ihr Login auf <a href="<?php echo $_SERVER['HTTP_HOST'] ?>">unserem Portal</a> wurde freigeschalten.
</p>
<?php elseif ($this->status == 2): ?>
<p>
    Hallo, <br /><br />
    Ihr Login auf <a href="<?php echo $_SERVER['HTTP_HOST'] ?>">unserem Portal</a> wurde gesperrt.
</p>
<?php endif; ?>
</body>
</html>