<?php
require_once (dirname(__FILE__) . '/../../helpers/OverlayHelper.php');
$objHelper = new OverlayHelper();
?>

<div class="oltitle"><?php echo $this->overlaytitle; ?></div>
<div class="spacer1"></div>
<div class="olnavigationwrapper">
    <?php echo $objHelper->getNavigationElements($this->elements, $this->viewtype, 0, $this->rootLevelId, $this->rootLevelType, $this->contenttype, $this->selectOne, $this->replace); ?>
</div>
<?php if ($this->rootLevelType == Zend_Registry::get('Core')->sysConfig->root_level_types->images) : ?>
<div class="contenthead">
    <?php echo $objHelper->getMediaFilter($this->rootLevelId, $this->viewtype, $this->contenttype); ?>
    <div id="mediaviewtypes">
        <div onclick="myOverlay.setViewType(1, 'ol_', false, <?php echo $this->replace ?> ); return false;" class="iconthumbview" id="ol_divThumbView"></div>
        <div onclick="myOverlay.setViewType(2, 'ol_', false, <?php echo $this->replace ?> ); return false;" class="iconlistview_on" id="ol_divListView"></div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<?php else: ?>
<div class="contenthead">
    <!-- SEARCH - not used now
   <div class="olsearch">
     <input type="text" id="mediaSearch" name="mediaSearch" value=""/>
     <div onclick="return false;" id="buttonsearch">
       <div class="button25leftOff"></div>
       <div class="button25centerOff">
         <img height="14" width="14" src="/zoolu-statics/images/icons/icon_search_white.png" class="iconsearch">
         <div>Suchen</div>
       </div>
       <div class="button25rightOff"></div>
       <div class="clear"></div>
     </div>
     <div class="clear"></div>
   </div> -->
    <?php echo $objHelper->getMediaFilter($this->rootLevelId, $this->viewtype, $this->contenttype); ?>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<?php endif; ?>
<div id="olContent" class="olcontentwrapper">
</div>
<div class="spacer1 clear"></div>