<?php
require_once (dirname(__FILE__) . '/../../helpers/OverlayHelper.php');
$objHelper = new OverlayHelper();
?>

<div class="oltitle"><?php echo $this->overlaytitle; ?></div>
<div class="spacer1"></div>
<div class="olnavigationwrapper">
    <?php echo $objHelper->getSitemapNavigationElements($this->elements); ?>
</div>
<div class="clear"></div>
<div id="olContent" class="olcontentwrapper">
</div>
<div class="spacer1 clear"></div>