<?php

require_once (dirname(__FILE__) . '/../../helpers/ListHelper.php');
$objHelper = new ListHelper();

?>
<input type="hidden" name="rootLevelFilterListId" id="rootLevelFilterListId" value="<?php echo $this->rootLevelFilterId; ?>"/>
<input type="hidden" name="rootLevelId" id="rootLevelId" value="<?php echo $this->rootLevelId; ?>"/>
<?php echo $objHelper->getList($this->paginator, $this->orderColumn, $this->sortOrder, $this->searchValue); ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<div class="spacer2"></div>
<script type="text/javascript">//<![CDATA[
if (typeof(myForm) != 'undefined' && typeof(myCore) != 'undefined') {
    myForm.blnShowFormAlert = <?php echo (($this->blnShowFormAlert == true) ? 'true' : 'false') ?>;
    myCore.deleteAlertMultiMessage = '<?php echo $this->translate->_('Delete_subscribers', false); ?>';
    myCore.deleteAlertSingleMessage = '<?php echo $this->translate->_('Delete_subscriber', false); ?>';
    if ($("importList"))
        $("importList").show();
    if ($("exportList"))
        $("exportList").show();
}
//]]>
</script>