<?php
/**
 * Groups configuration for default Minify implementation
 * @package Minify
 */

/**
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/min/builder/
 **/

return array(
    'zCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_font.css'),
    'zJs' => array(
        '//zoolu-statics/js_incs/prototype/prototype.js',
        '//zoolu-statics/js_incs/script.aculous/builder.js',
        '//zoolu-statics/js_incs/script.aculous/effects.js',
        '//zoolu-statics/js_incs/script.aculous/dragdrop.js',
        '//zoolu-statics/js_incs/script.aculous/controls.js',
        '//zoolu-statics/js_incs/script.aculous/slider.js'),
    'zDashboardCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/dashboard.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zDashboardJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout-dbrd.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/dashboard.js',
        '//zoolu-statics/js_incs/contentchooser.js'),
    'zExtCss' => array(
        '//zoolu-statics/js_incs/ext.js/resources/css/ext-all.css',
        '//zoolu-statics/js_incs/ext.js/resources/css/xtheme-gray.css'),
    'zCmsCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/tags.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zCmsListJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout2.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.cms.js',
        '//zoolu-statics/js_incs/navigation.landingpages.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.landingpages.js',
        '//zoolu-statics/js_incs/page.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/folder.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/tags.js'),
    'zCmsJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.cms.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/page.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/folder.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/tags.js',
        '//zoolu-statics/js_incs/dashboard.js',
        '//zoolu-statics/js_incs/contentchooser.js'),
    'zMediaCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/media.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zMediaJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.media.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/media.js',
        '//zoolu-statics/js_incs/folder.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/dashboard.js',
        '//zoolu-statics/js_incs/swfupload/swfupload.js',
        '//zoolu-statics/js_incs/swfupload/plugins/swfupload.swfobject.js',
        '//zoolu-statics/js_incs/swfupload/plugins/swfupload.queue.js',
        '//zoolu-statics/js_incs/swfupload/fileprogress.js',
        '//zoolu-statics/js_incs/swfupload/handlers.js'),
    'zGlobalCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/tags.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zGlobalListJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout2.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.global.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/global.js',
        '//zoolu-statics/js_incs/overlay.js'),
    'zGlobalTreeJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.global.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/global.js',
        '//zoolu-statics/js_incs/folder.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/tags.js',
        '//zoolu-statics/js_incs/dashboard.js',
        '//zoolu-statics/js_incs/contentchooser.js'),
    'zPropertyCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zPropertyJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.properties.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.properties.js',
        '//zoolu-statics/js_incs/overlay.js'),
    'zUserCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/tags.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zUserJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout2.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.users.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.users.js',
        '//zoolu-statics/js_incs/overlay.js'),
    'zContactCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/tags.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zContactListJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout2.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.contacts.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.contacts.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/filter.js'),
    'zContactTreeJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.contacts.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.contacts.js',
        '//zoolu-statics/js_incs/folder.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/tags.js'),
    'zNewsletterCss' => array(
        '//zoolu-statics/css/core_main.css',
        '//zoolu-statics/css/core_navigation.css',
        '//zoolu-statics/css/core_content.css',
        '//zoolu-statics/css/core_font.css',
        '//zoolu-statics/css/tags.css',
        '//zoolu-statics/css/facebooklist.css'),
    'zNewsletterListJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout2.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.newsletters.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.newsletters.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/tags.js'),
    'zNewsletterTreeJs' => array(
        '//zoolu-statics/js_incs/prototype/element.addons.js',
        '//zoolu-statics/js_incs/prototype/facebooklist.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/adapter/prototype/ext-prototype-adapter.js',
        '//zoolu-statics/js_incs/ext.js-3.4.0/ext-all.js',
        '//zoolu-statics/js_incs/core.js',
        '//zoolu-statics/js_incs/layout.js',
        '//zoolu-statics/js_incs/navigation.js',
        '//zoolu-statics/js_incs/navigation.newsletters.js',
        '//zoolu-statics/js_incs/list.js',
        '//zoolu-statics/js_incs/form.js',
        '//zoolu-statics/js_incs/form.newsletters.js',
        '//zoolu-statics/js_incs/folder.js',
        '//zoolu-statics/js_incs/overlay.js',
        '//zoolu-statics/js_incs/tags.js')
);