<?php

  require_once (dirname(__FILE__).'/../../helpers/NavigationHelper.php');
  $objHelper = new NavigationHelper();

?>
    
    <?php if($this->rootLevelId > 0 && $this->rootLevelGroupId > 0): ?>
    <script type="text/javascript">//<![CDATA[
      var rootLevelId = <?php echo $this->rootLevelId; ?>;
      var rootLevelGroupId = <?php echo $this->rootLevelGroupId; ?>;      
    //]]>
    </script>
    <?php endif; ?>

    <!-- navigation left -->
    <div id="navigation-left">

      <!-- navigation left -->
      <div id="navilefttop2">
        <img width="5" height="5" src="/zoolu-statics/images/main/bg_corner_top_left_white.png"/>
      </div>
      <div id="navirighttop2">
        <img width="5" height="5" src="/zoolu-statics/images/main/bg_corner_top_right_white.png"/>
      </div>
      <div id="divNaviLeft2">
        <div id="divNaviLeftInner">
          <!-- main navigatin -->
          <div id="divNaviLeftMain">
            <?php echo $objHelper->getMainNavigation($this->rootLevelNavigation, $this->rootLevelId, 'list'); ?>
          </div>
        </div>
      </div>

      <div id="navileftbottom2">
        <img width="5" height="5" src="/zoolu-statics/images/main/bg_corner_bottom_left_white.png"/>
      </div>
      <div id="navirightbottom2">
        <img width="5" height="5" src="/zoolu-statics/images/main/bg_corner_bottom_right_white.png"/>
      </div>
    </div> <!-- END navigation main -->