<?php
require_once (dirname(__FILE__) . '/../../helpers/ContentchooserHelper.php');
$objHelper = new ContentchooserHelper();
$objHelper->setTranslate($this->translate);

switch ($this->contenttype) {
    case 'media':
        echo $objHelper->getListView($this->elements, $this->relation);
        break;
    default:
        echo $objHelper->getListElements($this->elements, $this->relation, $this->contenttype);
        break;
}

?>