<?php
require_once (dirname(__FILE__) . '/../../helpers/ContentchooserHelper.php');
$objHelper = new ContentchooserHelper();
$objHelper->setTranslate($this->translate);
?>

<div class="olnavigationwrappercontent" <?php if($this->type == 'folder') echo 'style="height:350px;"' ?>>
    <?php echo $objHelper->getNavigationElements($this->elements, $this->viewtype, 0, $this->rootLevelId, $this->rootLevelTypeId, $this->rootLevelGroupId, $this->contenttype, $this->overlaytitle); ?>
</div>
<?php if($this->type == 'folder'): ?>
<div id="overlayButtons" class="overlaycontent" style="">
    <div id="buttonOk">
        <div class="button25leftOn"></div>
        <div class="button25centerOn">
            <div><?php echo $this->translate->_('Ok'); ?></div>
        </div>
        <div class="button25rightOn"></div>
        <div class="clear"></div>
    </div>
    <div id="buttonCancel">
        <div class="button25leftOff"></div>
        <div class="button25centerOff">
            <div><?php echo $this->translate->_('Cancel'); ?></div>
        </div>
        <div class="button25rightOff"></div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
<?php else: ?>
<div class="spacercontent">
</div>
<div id="olFolderContent" class="olcontentchoosercontentwrapper">
</div>
<?php endif; ?>
<input type="hidden" id="languageId" name="languageId" value=""/>