<?php
require_once (dirname(__FILE__) . '/../../helpers/ContentchooserHelper.php');
$objHelper = new ContentchooserHelper();
$objHelper->setTranslate($this->translate);
//echo $objHelper->getContentView($this->elements, $this->viewtype, $this->overlaytitle);
?>

<div class="olnavigationwrappercontent">
    <?php echo $objHelper->getNavigationElements($this->elements, $this->viewtype, 0, $this->rootLevelId, $this->rootLevelTypeId, $this->rootLevelGroupId, $this->contenttype, $this->overlaytitle); ?>
</div>
<div class="spacercontent">
</div>
<div id="olFolderContent" class="olcontentwrapper">
</div>
<input type="hidden" id="languageId" name="languageId" value=""/>