<?php
  require_once (dirname(__FILE__).'/../../helpers/OverlayHelper.php');
  $objHelper = new OverlayHelper();
?> 

<div class="oltitle"><?php echo $this->overlaytitle; ?></div>
<div class="spacer1"></div>
<div class="olnavigationwrapper">
  <?php echo $objHelper->getNavigationElements($this->elements, $this->viewtype); ?>  
</div>
<div class="spacer1"></div>
<div id="olContent" class="olcontentwrapper">
</div>
<div class="spacer1 clear"></div>