<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>ZOOLU - <?php echo $this->translate->_('contacts'); ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Language" content="de"/>
    <meta name="language" content="de"/>

    <link href="/min/g=zExtCss?v=<?php echo $this->jsVersion; ?>" rel="stylesheet"/>
    <link href="/min/g=zContactCss?v=<?php echo $this->jsVersion; ?>" rel="stylesheet"/>

</head>
<body id="myBody">

    <!-- navigation top -->
    <div id="navigation-top">

        <div id="top">

            <div class="toplogo">
                <a href="/zoolu">
                    <img src="/zoolu-statics/images/main/logo_zoolu_small.png" width="69" height="17" alt="ZOOLU"/>
                </a>
            </div>
            <div class="topright">
                <div class="openWebsite"><a href="/" target="_blank"><?php echo $this->translate->_('Open_website'); ?></a>
                </div>
                <div class="faqtitle"> |
                    <a href="https://github.com/massiveart-webservices/ZOOLU" target="_blank"><?php echo $this->translate->_('Report_bugs'); ?></a> |
                    <a href="http://documentation.getzoolu.org/"><?php echo $this->translate->_('Help_and_FAQ'); ?></a>
                </div>
                <div class="faqicon"><img src="/zoolu-statics/images/icons/icon_help.png" width="16" height="16"/></div>
                <div class="clear"></div>
            </div>

            <div class="clear"></div>
        </div>
        <!-- END top -->

        <?php echo $this->layout()->userinfo; ?>

        <div id="navtopwrapper">
            <?php echo $this->layout()->modules; ?>
            <div id="navtopbreadcrumb" style="display:none;"></div>
        </div>

    </div>
    <!-- END navigation top -->

    <?php echo $this->layout()->navigation; ?>

    <!-- content -->
    <div id="content">

        <!-- widget: save, delete, infos, ... -->
        <div id="genListFunctions" style="display:none;">
            <div class="widgetfunctions">
                <div class="widgetcontenttop">
                    <!-- new button -->
                    <div id="buttonnew" onclick="myNavigation.getAddForm();">
                        <div class="button25leftOn"></div>
                        <div class="button25centerOn">
                            <img class="iconsave" src="/zoolu-statics/images/icons/icon_save_black.png" width="13" height="13"/>

                            <div><?php echo $this->translate->_('New'); ?></div>
                        </div>
                        <div class="button25rightOn"></div>
                        <div class="clear"></div>
                    </div>

                    <!-- edit menu -->
                    <div id="buttonedit" onclick="return false;">
                        <div class="buttonedittop"></div>
                        <div id="buttonmediaedittitle" class="buttoneditmiddle white" onclick="myList.toggleEditMenu(this.id); return false;"><?php echo $this->translate->_('Edit'); ?></div>
                        <div class="buttoneditbottom"></div>
                        <div class="clear"></div>
                    </div>

                    <div id="buttonEditMenu" class="buttoneditmenu" style="display:none;">
                        <div class="buttoneditmenuinner">
                            <div class="buttoneditlink" onclick="myList.deleteListItem(); return false;"><?php echo $this->translate->_('Delete'); ?></div>
                            <div class="clear"></div>
                        </div>
                        <div class="buttoneditbottom"></div>
                        <div class="clear"></div>
                    </div>

                    <!-- search container -->
                    <div id="searchContainer" class="searchContainer">
                        <input type="text" id="search" name="search" class="searchInput" value=""/>
                        <!-- delete button -->
                        <div id="buttonsearch" onclick="myList.search();">
                            <div class="button25leftOff"></div>
                            <div class="button25centerOff">
                                <img class="icondelete" src="/zoolu-statics/images/icons/icon_search_white.png" width="14" height="14"/>

                                <div><?php echo $this->translate->_('Search'); ?></div>
                            </div>
                            <div class="button25rightOff"></div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <!-- content list -->
        <div id="genListContainer" class="contentedit2" style="display:none;"></div>

        <!-- content edit -->
        <div id="genFormContainer" class="contentedit" style="display:none;">
        </div>

        <!-- content function widget -->
        <div id="genFormSaveContainer" class="contentfunction" style="display:none;">

            <!-- widget: save, delete, infos, ... -->
            <div class="widgetfunctions">
                <div class="widget224content">
                    <div class="widgetcontenttop">

                        <!-- alerts for saving, editing, deleting, ... -->
                        <div id="divFormSaveLoader" class="alertsave" style="display:none;">
                            <div class="alertsaveloader white">
                                <img src="/zoolu-statics/images/main/loader_save.gif"/><a href="#" onclick="myForm.cancleFormSaveLoader(); return false;" style="color:#fff;"><?php echo $this->translate->_('Cancel'); ?></a>
                            </div>
                        </div>
                        <div id="divFormSaveSucces" class="alertsavesucces" style="display:none;"><?php echo $this->translate->_('Saved'); ?>!</div>
                        <div id="divFormSaveError" class="alertsaveerror" style="display:none;"><?php echo $this->translate->_('Can_not_Save'); ?>!</div>
                        <div id="divFormDeleteSucces" class="alertdeletesucces" style="display:none;"><?php echo $this->translate->_('Deleted'); ?>!</div>

                        <!-- save button -->
                        <div id="buttonsave" onclick="myForm.save();">
                            <div class="button25leftOn"></div>
                            <div class="button25centerOn">
                                <img class="iconsave" src="/zoolu-statics/images/icons/icon_save_black.png" width="13" height="13"/>

                                <div><?php echo $this->translate->_('Save'); ?></div>
                            </div>
                            <div class="button25rightOn"></div>
                            <div class="clear"></div>
                        </div>

                        <!-- delete button -->
                        <div id="buttondelete" onclick="myForm.deleteElement();" style="display:none;">
                            <div class="button25leftOff"></div>
                            <div class="button25centerOff">
                                <img class="icondelete" src="/zoolu-statics/images/icons/icon_delete_white.png" width="11" height="14"/>

                                <div><?php echo $this->translate->_('Delete'); ?></div>
                            </div>
                            <div class="button25rightOff"></div>
                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>
                    </div>

                    <div class="widgetcontentmain" id="divWidgetMetaInfos">
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- END content -->

    <!-- overlay transparent-->
    <div id="overlayTrans" class="overlaytrans" style="display:none;"></div>
    <!-- overlay black 75% -->
    <div id="overlayBlack75" class="overlayblack75" style="display:none;" onclick="myOverlay.close();"></div>

    <!-- overlay for user settings -->
    <div id="overlayUserSettingsWrapper" class="overlaycontentwrapper" style="display:none;">
        <table>
            <thead>
            <tr>
                <td class="cornertopleft"></td>
                <td class="topcenter"></td>
                <td class="cornertopright"></td>
            </tr>
            <tr>
                <td class="headerleft"></td>
                <td class="headercenter handle">
                    <div class="headerclose" onclick="myOverlay.closeUserSettingsOverlay(); return false;"></div>
                    <div class="clear"></div>
                </td>
                <td class="headerright"></td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="contentleft"></td>
                <td class="contentcenter">
                    <!-- content -->
                    <div class="overlaycontent">
                        <div class="oltitle"><?php echo $this->translate->_('My_Settings'); ?></div>
                        <div class="spacer1"></div>
                        <div id="overlayUserSettingsContent" class="propertywrapper">
                        </div>
                        <div class="clear"></div>
                        <div onclick="myOverlay.closeUserSettingsOverlay(); return false;" class="buttoncancel"><?php echo $this->translate->_('Cancel'); ?></div>
                        <div class="buttoneditsave" onclick="myForm.saveUserSettings();">
                            <div class="button25leftOn"></div>
                            <div class="button25centerOn">
                                <img width="13" height="13" class="iconsave" src="/zoolu-statics/images/icons/icon_save_black.png"/>

                                <div><?php echo $this->translate->_('Save'); ?></div>
                            </div>
                            <div class="button25rightOn"></div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </td>
                <td class="contentright"></td>
            </tr>
            <tr>
                <td class="cornerbottomleft"></td>
                <td class="bottomcenter"></td>
                <td class="cornerbottomright"></td>
            </tr>
            </tbody>
        </table>
    </div>

    <!-- overlay for generated content -->
    <div id="overlayGenContentWrapper" class="overlaycontentwrapper" style="display:none;">
        <table>
            <thead>
            <tr>
                <td class="cornertopleft"></td>
                <td class="topcenter"></td>
                <td class="cornertopright"></td>
            </tr>
            <tr>
                <td class="headerleft"></td>
                <td class="headercenter handle">
                    <div class="headerclose" onclick="myOverlay.close('overlayGenContentWrapper'); return false;"></div>
                    <div class="clear"></div>
                </td>
                <td class="headerright"></td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="contentleft"></td>
                <td class="contentcenter">
                    <!-- cotnent -->
                    <div id="overlayGenContent" class="overlaycontent"></div>
                    <!-- buttons -->
                    <div id="overlayButtons" class="overlaycontent" style="display:none;">
                        <div id="buttonOk">
                            <div class="button25leftOn"></div>
                            <div class="button25centerOn">
                                <!-- <img width="13" height="13" src="/zoolu-statics/images/icons/icon_ok_black.png" class="iconok"/> -->
                                <div><?php echo $this->translate->_('Ok'); ?></div>
                            </div>
                            <div class="button25rightOn"></div>
                            <div class="clear"></div>
                        </div>
                        <div id="buttonCancel">
                            <div class="button25leftOff"></div>
                            <div class="button25centerOff">
                                <!-- <img width="11" height="14" src="/zoolu-statics/images/icons/icon_cancel_white.png" class="iconcancel"/> -->
                                <div><?php echo $this->translate->_('Cancel'); ?></div>
                            </div>
                            <div class="button25rightOff"></div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </td>
                <td class="contentright"></td>
            </tr>
            <tr>
                <td class="cornerbottomleft"></td>
                <td class="bottomcenter"></td>
                <td class="cornerbottomright"></td>
            </tr>
            </tbody>
        </table>
    </div>

    <!-- libaries -->
    <script type="text/javascript" src="/min/g=zJs?v=<?php echo $this->jsVersion; ?>&debug=1"></script>
    <script type="text/javascript" src="/min/g=zContactTreeJs?v=<?php echo $this->jsVersion; ?>&debug=1"></script>
    <script type="text/javascript" src="/zoolu-statics/tinymce/js/tinymce/tinymce.min.js?v=<?php echo $this->jsVersion; ?>"></script>

    <?php echo $this->jsPlugins; ?>

    <script type="text/javascript">//<![CDATA[
    var myCore, myNavigation, myForm, myFolder, myOverlay, myList;

    //document.observe('dom:loaded', function() {
    Event.observe(window, 'load', function() {
        myCore = new Massiveart.Core();

        myCore.languageId = <?php echo Zend_Registry::get('Core')->intZooluLanguageId; ?>;
        myCore.languageCode = '<?php echo Zend_Registry::get('Core')->strZooluLanguageCode; ?>';

        myNavigation = new Massiveart.Navigation.Contacts();
        myList = new Massiveart.List();
        myList.ItemsPerPage = <?php echo Zend_Registry::get('Core')->sysConfig->list->default->itemsPerPage; ?>;
        myForm = new Massiveart.Form.Contacts();
        myFolder = new Massiveart.Folder();
        myOverlay = new Massiveart.Overlay();

        myCore.translate = {
            Save: '<?php echo $this->translate->_('Save'); ?>',
            Cancel: '<?php echo $this->translate->_('Cancel'); ?>',
            Apply: '<?php echo $this->translate->_('Apply'); ?>',
            Edit: '<?php echo $this->translate->_('Edit'); ?>',
            Delete_: '<?php echo $this->translate->_('Delete_'); ?>',
            Delete_unit: '<?php echo $this->translate->_('Delete_unit'); ?>',
            Delete_location: '<?php echo $this->translate->_('Delete_location'); ?>',
            Delete_contact: '<?php echo $this->translate->_('Delete_contact'); ?>'
        };

        myNavigation.topNaviTitle = '<?php echo $this->translate->_('contacts'); ?>';
        myNavigation.module = <?php echo $this->module; ?>;

        if ((typeof(rootLevelId) != 'undefined') && (typeof(rootLevelGroupId) != 'undefined')) {
            myNavigation.setRootLevelId(rootLevelId);
            myNavigation.setRootLevelGroupId(rootLevelGroupId);
            myNavigation.getRootLevelTreeStart();
        }

        if ((typeof(preSelectedNaviItem) != 'undefined')) {
            myNavigation.preSelectedNaviItem = preSelectedNaviItem;
        }

        if ((typeof(preSelectedSubNaviItem) != 'undefined')) {
            myNavigation.preSelectedSubNaviItem = preSelectedSubNaviItem;
        }

        new Draggable('overlayGenContentWrapper', {handle: 'handle', scroll: window });
    });

    //]]>
    </script>
</body>
</html>