<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>ZOOLU - <?php echo $this->translate->_('tags_administration'); ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Language" content="de"/>
    <meta name="language" content="de"/>

    <meta http-equiv="X-UA-Compatible" content="IE=7, IE=9, chrome=1" />

    <link href="/min/g=zExtCss?v=<?php echo $this->jsVersion; ?>" rel="stylesheet"/>
    <link href="/min/g=zPropertyCss?v=<?php echo $this->jsVersion; ?>" rel="stylesheet"/>
</head>
<body id="myBody">

<!-- navigation top -->
<div id="navigation-top">

    <div id="top">

        <div class="toplogo">
            <a href="/zoolu">
                <img src="/zoolu-statics/images/main/logo_zoolu_small.png" width="69" height="17" alt="ZOOLU"/>
            </a>
        </div>
        <div class="topright">
            <div class="openWebsite"><a href="/" target="_blank"><?php echo $this->translate->_('Open_website'); ?></a>
            </div>
            <div class="faqtitle"> |
                <a href="https://github.com/massiveart-webservices/ZOOLU" target="_blank"><?php echo $this->translate->_('Report_bugs'); ?></a> |
                <a href="http://documentation.getzoolu.org/"><?php echo $this->translate->_('Help_and_FAQ'); ?></a>
            </div>
            <div class="faqicon"><img src="/zoolu-statics/images/icons/icon_help.png" width="16" height="16"/></div>
            <div class="clear"></div>
        </div>

        <div class="clear"></div>
    </div>
    <!-- END top -->

    <?php echo $this->layout()->userinfo; ?>

    <div id="navtopwrapper">
        <?php echo $this->layout()->modules; ?>
        <div id="navtopbreadcrumb" style="display:none;"></div>
    </div>

</div>
<!-- END navigation top -->

<?php echo $this->layout()->navigation; ?>

<!-- content -->
<div id="content2">

    <!-- widget: save, delete, infos, ... -->
    <div class="widgetfunctions">
        <div class="widgetcontenttop">

            <!-- alerts for saving, editing, deleting, ... -->
            <div id="divFormSaveLoader" class="alertsave" style="display:none;">
                <div class="alertsaveloader white">
                    <img src="/zoolu-statics/images/main/loader_save_gray.gif"/><a href="#" onclick="myForm.cancleFormSaveLoader(); return false;" style="color:#fff;"><?php echo $this->translate->_('Cancel'); ?></a>
                </div>
            </div>
            <div id="divFormSaveSucces" class="alertsavesucces" style="display:none;"><?php echo $this->translate->_('Saved'); ?>!</div>
            <div id="divFormSaveError" class="alertsaveerror" style="display:none;"><?php echo $this->translate->_('Can_not_Save'); ?>!</div>
            <div id="divFormDeleteSucces" class="alertdeletesucces" style="display:none;"><?php echo $this->translate->_('Deleted'); ?>!</div>

            <div id="genListFunctions" style="display:none;">
                <!-- new button -->
                <div id="buttonnew" onclick="myNavigation.getAddFormList();">
                    <div class="button25leftOn"></div>
                    <div class="button25centerOn">
                        <img class="iconsave" src="/zoolu-statics/images/icons/icon_save_black.png" width="13" height="13"/>

                        <div><?php echo $this->translate->_('New'); ?></div>
                    </div>
                    <div class="button25rightOn"></div>
                    <div class="clear"></div>
                </div>

                <!-- edit menu -->
                <div id="buttonedit" onclick="return false;">
                    <div class="buttonedittop"></div>
                    <div id="buttonmediaedittitle" class="buttoneditmiddle white" onclick="myList.toggleEditMenu(this.id); return false;"><?php echo $this->translate->_('Edit'); ?></div>
                    <div class="buttoneditbottom"></div>
                    <div class="clear"></div>
                </div>

                <div id="buttonEditMenu" class="buttoneditmenu" style="display:none;">
                    <div class="buttoneditmenuinner">
                        <div class="buttoneditlink" onclick="myTags.getMergeTagForm(); return false;"><?php echo $this->translate->_('Merge_tags'); ?></div>
                        <div class="clear"></div>
                        <div class="buttoneditlink" onclick="myList.deleteListItem(); return false;"><?php echo $this->translate->_('Delete'); ?></div>
                        <div class="clear"></div>
                    </div>
                    <div class="buttoneditbottom"></div>
                    <div class="clear"></div>
                </div>

                <!-- search container -->
                <div id="searchContainer" class="searchContainer">
                    <input type="text" id="search" name="search" class="searchInput" value=""/>
                    <!-- delete button -->
                    <div id="buttonsearch" onclick="myList.search();">
                        <div class="button25leftOff"></div>
                        <div class="button25centerOff">
                            <img class="icondelete" src="/zoolu-statics/images/icons/icon_search_white.png" width="14" height="14"/>

                            <div><?php echo $this->translate->_('Search'); ?></div>
                        </div>
                        <div class="button25rightOff"></div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>

            <div id="genFormFunctions" style="display:none;">
                <!-- back link to list -->
                <div id="backlink">
                    <a href="#" onclick="myList.backFilter(); return false;">&laquo; <?php echo $this->translate->_('back'); ?></a>
                </div>
                <!-- save button -->
                <div id="buttonsave" onclick="myForm.saveTag();">
                    <div class="button25leftOn"></div>
                    <div class="button25centerOn">
                        <img class="iconsave" src="/zoolu-statics/images/icons/icon_save_black.png" width="13" height="13"/>

                        <div><?php echo $this->translate->_('Save'); ?></div>
                    </div>
                    <div class="button25rightOn"></div>
                    <div class="clear"></div>
                </div>

                <!-- delete button -->
                <div id="buttondelete" onclick="myForm.deleteTagElement();">
                    <div class="button25leftOff"></div>
                    <div class="button25centerOff">
                        <img class="icondelete" src="/zoolu-statics/images/icons/icon_delete_white.png" width="11" height="14"/>

                        <div><?php echo $this->translate->_('Delete'); ?></div>
                    </div>
                    <div class="button25rightOff"></div>
                    <div class="clear"></div>
                </div>
            </div>

            <div class="clear"></div>
        </div>
    </div>

    <div id="genTmpContainer" style="display:none;"></div>

    <div id="genFormContainer" class="contentedit2" style="display:none;"></div>

    <div id="genListContainer" class="contentedit2" style="display:none;"></div>
</div>

<!-- overlay transparent-->
<div id="overlayTrans" class="overlaytrans" style="display:none;"></div>
<!-- overlay black 75% -->
<div id="overlayBlack75" class="overlayblack75" style="display:none;" onclick="myOverlay.close();"></div>

<!-- overlay for user settings -->
<div id="overlayUserSettingsWrapper" class="overlaycontentwrapper" style="display:none;">
    <table>
        <thead>
        <tr>
            <td class="cornertopleft"></td>
            <td class="topcenter"></td>
            <td class="cornertopright"></td>
        </tr>
        <tr>
            <td class="headerleft"></td>
            <td class="headercenter handle">
                <div class="headerclose" onclick="myOverlay.closeUserSettingsOverlay(); return false;"></div>
                <div class="clear"></div>
            </td>
            <td class="headerright"></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="contentleft"></td>
            <td class="contentcenter">
                <!-- content -->
                <div class="overlaycontent">
                    <div class="oltitle"><?php echo $this->translate->_('My_Settings'); ?></div>
                    <div class="spacer1"></div>
                    <div id="overlayUserSettingsContent" class="propertywrapper">
                    </div>
                    <div class="clear"></div>
                    <div onclick="myOverlay.closeUserSettingsOverlay(); return false;" class="buttoncancel"><?php echo $this->translate->_('Cancel'); ?></div>
                    <div class="buttoneditsave" onclick="myForm.saveUserSettings();">
                        <div class="button25leftOn"></div>
                        <div class="button25centerOn">
                            <img width="13" height="13" class="iconsave" src="/zoolu-statics/images/icons/icon_save_black.png"/>

                            <div><?php echo $this->translate->_('Save'); ?></div>
                        </div>
                        <div class="button25rightOn"></div>
                        <div class="clear"></div>
                    </div>
                </div>
            </td>
            <td class="contentright"></td>
        </tr>
        <tr>
            <td class="cornerbottomleft"></td>
            <td class="bottomcenter"></td>
            <td class="cornerbottomright"></td>
        </tr>
        </tbody>
    </table>
</div>

<!-- overlay for generated content -->
<div id="overlayGenContentWrapper" class="overlaycontentwrapper" style="display:none;">
    <table>
        <thead>
        <tr>
            <td class="cornertopleft"></td>
            <td class="topcenter"></td>
            <td class="cornertopright"></td>
        </tr>
        <tr>
            <td class="headerleft"></td>
            <td class="headercenter handle">
                <div class="headerclose" onclick="myOverlay.close('overlayGenContentWrapper'); return false;"></div>
                <div class="clear"></div>
            </td>
            <td class="headerright"></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="contentleft"></td>
            <td class="contentcenter">
                <!-- cotnent -->
                <div id="overlayGenContent" class="overlaycontent"></div>
                <!-- buttons -->
                <div id="overlayButtons" class="overlaycontent" style="display:none;">
                    <div id="buttonOk">
                        <div class="button25leftOn"></div>
                        <div class="button25centerOn">
                            <!-- <img width="13" height="13" src="/zoolu-statics/images/icons/icon_ok_black.png" class="iconok"/> -->
                            <div><?php echo $this->translate->_('Ok'); ?></div>
                        </div>
                        <div class="button25rightOn"></div>
                        <div class="clear"></div>
                    </div>
                    <div id="buttonCancel">
                        <div class="button25leftOff"></div>
                        <div class="button25centerOff">
                            <!-- <img width="11" height="14" src="/zoolu-statics/images/icons/icon_cancel_white.png" class="iconcancel"/> -->
                            <div><?php echo $this->translate->_('Cancel'); ?></div>
                        </div>
                        <div class="button25rightOff"></div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            </td>
            <td class="contentright"></td>
        </tr>
        <tr>
            <td class="cornerbottomleft"></td>
            <td class="bottomcenter"></td>
            <td class="cornerbottomright"></td>
        </tr>
        </tbody>
    </table>
</div>
<!-- END overlay for generated content -->

<!-- libaries -->
<script type="text/javascript" src="/min/g=zJs?v=<?php echo $this->jsVersion; ?>"></script>
<script type="text/javascript" src="/min/g=zPropertyListJs?v=<?php echo $this->jsVersion; ?>"></script>
<script type="text/javascript" src="/zoolu-statics/tinymce/jscripts/tiny_mce/tiny_mce.js?v=<?php echo $this->jsVersion; ?>"></script>
<?php echo $this->jsPlugins; ?>

<script type="text/javascript">//<![CDATA[
    var myCore, myNavigation, myList, myForm, myOverlay;
    //document.observe('dom:loaded', function() {
    Event.observe(window, 'load', function() {
        myCore = new Massiveart.Core();
        myCore.translate = {
            Save: '<?php echo $this->translate->_('Save'); ?>',
            Edit: '<?php echo $this->translate->_('Edit'); ?>',
            Delete_: '<?php echo $this->translate->_('Delete_'); ?>'
        };

        myNavigation = new Massiveart.Navigation.Properties();
        myList = new Massiveart.List();
        myList.ItemsPerPage = <?php echo Zend_Registry::get('Core')->sysConfig->list->default->itemsPerPage; ?>;
        myForm = new Massiveart.Form.Properties();
        myOverlay = new Massiveart.Overlay();

        myNavigation.topNaviTitle = '<?php echo $this->translate->_('tags'); ?>';
        myNavigation.module = <?php echo $this->module; ?>;

        if ((typeof(rootLevelId) != 'undefined') && (typeof(rootLevelGroupId) != 'undefined')) {
            myNavigation.setRootLevelId(rootLevelId);
            myNavigation.setRootLevelGroupId(rootLevelGroupId);
            myNavigation.getRootLevelTreeStart();
        }

        if ((typeof(preSelectedNaviItem) != 'undefined')) {
            myNavigation.preSelectedNaviItem = preSelectedNaviItem;
        }

        new Draggable('overlayGenContentWrapper', {handle: 'handle', scroll: window });
    });

    //]]>
</script>
</body>
</html>