<?php
  require_once (dirname(__FILE__).'/../../helpers/FolderHelper.php');
  $objHelper = new FolderHelper();
?> 

<div class="oltitle"><?php echo $this->overlaytitle; ?></div>
<div class="spacer1"></div>
<div class="olnavigationwrapper2">
  <div class="field">
    <form id="foderCheckboxTreeForm" onsubmit="return false;">
      <?php echo $objHelper->getFolderCheckboxTree($this->elements, $this->selectedRootLevelId, $this->selectedFolderIds); ?>
    </form>
  </div>
</div>
<div class="spacer1 clear"></div>
<div style="float:right">
  <div id="buttonsave" onclick="myOverlay.selectDocumentFolders();">
    <div class="button25leftOn"></div>
    <div class="button25centerOn">
      <div><?php echo $this->translate->_('Apply'); ?></div>
    </div>
    <div class="button25rightOn"></div>
  </div>
</div>
<div class="spacer1 clear"></div>