<?php
  require_once (dirname(__FILE__).'/../../helpers/FolderHelper.php');
  $objHelper = new FolderHelper();
?> 

                 <div class="formtitle"><?php echo $this->listTitle; ?></div>
                 <table class="tablelist">
                   <thead>
                     <tr>
                       <th class="topcornerleft"></th>
                       <th class="topcheckbox"></th>
                       <th class="topicon"></th>
                       <th class="toptitle"><?php echo $this->translate->_('title'); ?></th>
                       <th class="topauthor"><?php echo $this->translate->_('Author'); ?></th>
                       <th class="topcornerright"></th>
                     </tr>
                   </thead>
                   <tbody>
                    <?php echo $objHelper->getFolderContentList($this->objFolderContent, $this->intFolderId); ?>
                   </tbody>
                 </table>
                 <div class="listfooter">
                   <div class="listfootercornerleft"></div>
                   <div class="listfootercornerright"></div>
                 </div>
                 <div class="spacer2"></div>