<?php
require_once (dirname(__FILE__) . '/../../helpers/FolderHelper.php');
$objHelper = new FolderHelper();
?>

<div class="contenthead">
    <!-- search container -->
    <div id="searchContainer" class="searchContainer">
        <input type="text" id="search" name="search" class="searchInput" value=""/>
        <!-- delete button -->
        <div id="buttonsearch" onclick="myList.search();">
            <div class="button25leftOff"></div>
            <div class="button25centerOff">
                <img class="icondelete" src="/zoolu-statics/images/icons/icon_search_white.png" width="14" height="14"/>

                <div><?php echo $this->translate->_('Search'); ?></div>
            </div>
            <div class="button25rightOff"></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="listContainer contentedit3">
    <?php echo $objHelper->getFolderContentListTitle($this->folderPaginator, $this->strSearchValue); ?>
    <table class="tablelist">
        <?php echo $objHelper->getFolderContentList($this->folderPaginator, $this->intFolderId, $this->currLevel, $this->strOrderColumn, $this->strOrderSort); ?>
    </table>
    <?php echo $this->paginationControl($this->folderPaginator, 'Sliding', 'pagination.phtml'); ?>
    <div class="spacer2"></div>
</div>
                 