<?php
  require_once (dirname(__FILE__).'/../../helpers/FolderHelper.php');
  $objHelper = new FolderHelper();
?>

<div class="tabNavContainer">
  <ul>
    <li id="tabNavItem_ZOOLU" class="item selected" onclick="myOverlay.selectTab('ZOOLU'); return false;">
      <div class="start"></div>
      <div class="middle"><a href="#">ZOOLU</a></div>
      <div class="end"></div>
    </li>
    <li id="tabNavItem_Website" class="item" onclick="myOverlay.selectTab('Website'); return false;">
      <div class="start"></div>
      <div class="middle"><a href="#"><?php echo $this->translate->_('Website')?></a></div>
      <div class="end"></div>
    </li>
  </ul>
</div>
<div class="spacer1"></div>
<form id="folderSecurityForm" method="post" onsubmit="return false;">
  <input name="folderId" type="hidden" value="<?php echo $this->folderId; ?>"/>
  <div class="olcontentwrappertab">
    <?php echo $objHelper->getFolderSecurity($this->folderSecurity); ?>
  </div>
</form>
<script type="text/javascript" language="javascript">//<![CDATA[
  myOverlay.setActiveTab('ZOOLU');
//]]>
</script>
<div class="spacer1 clear"></div>
<div style="float: right;">
  <div id="buttonsave" onclick="myFolder.updateFolderSecurity();">
    <div class="button25leftOn"></div>
    <div class="button25centerOn"><img class="iconsave" width="13" height="13" src="/zoolu-statics/images/icons/icon_save_black.png"/><div><?php echo $this->translate->_('Save')?></div></div>
    <div class="button25rightOn"></div>
    <div class="clear"></div>
  </div>
</div>
<div class="spacer1 clear"></div>